movimientos= [
    {"id": 1, "monto": 151.00, "descripcion": "Tienda", "cuenta": "Cash", "categoria": "Groceries", "comentario": "Pan y leche", "fecha": "2025-06-26"},
    {"id": 2, "monto": 180.50, "descripcion": "Super 4", "cuenta": "Savings", "categoria": "Utilities", "comentario": "Luz y agua", "fecha": "2025-07-01"},
    {"id": 3, "monto": 251.00, "descripcion": "Tienda test0004", "cuenta": "Cash", "categoria": "Groceries", "comentario": "Pan y leche", "fecha": "2025-06-25"},
    {"id": 4, "monto": 350.75, "descripcion": "Pago internet", "cuenta": "Checking", "categoria": "Utilities", "comentario": "Internet mensual", "fecha": "2025-07-02"},
    {"id": 5, "monto": 120.00, "descripcion": "Restaurante Pizza", "cuenta": "Cash", "categoria": "Restaurants", "comentario": "Almuerzo", "fecha": "2025-07-03"},
    {"id": 6, "monto": 480.20, "descripcion": "Gasolina", "cuenta": "Checking", "categoria": "Transportation", "comentario": "Llenar tanque", "fecha": "2025-07-04"},
    {"id": 7, "monto": 75.00, "descripcion": "Cine", "cuenta": "Savings", "categoria": "Entertainment", "comentario": "Película", "fecha": "2025-07-05"},
    {"id": 8, "monto": 230.90, "descripcion": "Pago Netflix", "cuenta": "Checking", "categoria": "Entertainment", "comentario": "Suscripción", "fecha": "2025-07-06"},
    {"id": 9, "monto": 100.00, "descripcion": "Pago Spotify", "cuenta": "Checking", "categoria": "Subscriptions", "comentario": "Música", "fecha": "2025-07-07"},
    {"id": 10, "monto": 85.00, "descripcion": "Ropa nueva", "cuenta": "Cash", "categoria": "Clothing", "comentario": "Camisa", "fecha": "2025-07-08"},
    {"id": 11, "monto": 330.00, "descripcion": "Pago luz", "cuenta": "Checking", "categoria": "Utilities", "comentario": "Factura de luz", "fecha": "2025-07-09"},
    {"id": 12, "monto": 90.50, "descripcion": "Restaurante Sushi", "cuenta": "Cash", "categoria": "Restaurants", "comentario": "Cena", "fecha": "2025-07-10"},
    {"id": 13, "monto": 215.00, "descripcion": "Consulta médica", "cuenta": "Savings", "categoria": "Medical & Healthcare", "comentario": "Chequeo anual", "fecha": "2025-07-11"},
    {"id": 14, "monto": 66.60, "descripcion": "Camiseta", "cuenta": "Cash", "categoria": "Clothing", "comentario": "Tienda deportiva", "fecha": "2025-07-12"},
    {"id": 15, "monto": 147.99, "descripcion": "Veterinario", "cuenta": "Checking", "categoria": "Pets", "comentario": "Desparasitación", "fecha": "2025-07-13"},
    {"id": 16, "monto": 190.25, "descripcion": "Mercado", "cuenta": "Cash", "categoria": "Groceries", "comentario": "Verduras", "fecha": "2025-07-14"},
    {"id": 17, "monto": 49.00, "descripcion": "Transporte", "cuenta": "Checking", "categoria": "Transportation", "comentario": "Bus", "fecha": "2025-07-15"},
    {"id": 18, "monto": 75.00, "descripcion": "Pago Disney+", "cuenta": "Savings", "categoria": "Subscriptions", "comentario": "Disney mensual", "fecha": "2025-07-16"},
    {"id": 19, "monto": 300.00, "descripcion": "Renta", "cuenta": "Checking", "categoria": "Housing", "comentario": "Apartamento", "fecha": "2025-07-17"},
    {"id": 20, "monto": 55.25, "descripcion": "Golosinas", "cuenta": "Cash", "categoria": "Groceries", "comentario": "Snacks", "fecha": "2025-07-18"},
    {"id": 21, "monto": 40.00, "descripcion": "Corte cabello", "cuenta": "Cash", "categoria": "Miscellaneous", "comentario": "Barbería", "fecha": "2025-07-19"},
    {"id": 22, "monto": 99.00, "descripcion": "Taxi", "cuenta": "Checking", "categoria": "Transportation", "comentario": "Viaje al centro", "fecha": "2025-07-20"},
    {"id": 23, "monto": 178.75, "descripcion": "Poliza seguro", "cuenta": "Savings", "categoria": "Insurance", "comentario": "Pago anual", "fecha": "2025-07-21"},
    {"id": 24, "monto": 65.00, "descripcion": "Snack", "cuenta": "Cash", "categoria": "Groceries", "comentario": "Dulces", "fecha": "2025-07-22"},
    {"id": 25, "monto": 125.99, "descripcion": "Veterinario gato", "cuenta": "Checking", "categoria": "Pets", "comentario": "Vacunas", "fecha": "2025-07-23"},
    {"id": 26, "monto": 345.00, "descripcion": "Libros niños", "cuenta": "Savings", "categoria": "Education", "comentario": "Escuela", "fecha": "2025-07-24"},
    {"id": 27, "monto": 80.00, "descripcion": "Ropa hijos", "cuenta": "Cash", "categoria": "Kids", "comentario": "Uniformes", "fecha": "2025-07-25"},
    {"id": 28, "monto": 289.99, "descripcion": "Seguro salud", "cuenta": "Checking", "categoria": "Medical & Healthcare", "comentario": "Pago anual", "fecha": "2025-07-26"},
    {"id": 29, "monto": 150.00, "descripcion": "Comida rápida", "cuenta": "Cash", "categoria": "Restaurants", "comentario": "Hamburguesa", "fecha": "2025-07-27"},
    {"id": 30, "monto": 99.99, "descripcion": "Suscripción Spotify", "cuenta": "Savings", "categoria": "Subscriptions", "comentario": "Familiar", "fecha": "2025-07-28"},
    {"id": 31, "monto": 176.45, "descripcion": "Gas", "cuenta": "Checking", "categoria": "Utilities", "comentario": "Cocina", "fecha": "2025-07-29"},
    {"id": 32, "monto": 63.50, "descripcion": "Snacks hijos", "cuenta": "Cash", "categoria": "Kids", "comentario": "Galletas", "fecha": "2025-07-30"},
    {"id": 33, "monto": 212.00, "descripcion": "Paseo", "cuenta": "Checking", "categoria": "Entertainment", "comentario": "Parque", "fecha": "2025-07-31"},
    {"id": 34, "monto": 129.00, "descripcion": "Zapatos", "cuenta": "Cash", "categoria": "Clothing", "comentario": "Deportivos", "fecha": "2025-08-01"},
    {"id": 35, "monto": 45.50, "descripcion": "Taxi regreso", "cuenta": "Checking", "categoria": "Transportation", "comentario": "Casa", "fecha": "2025-08-02"},
    {"id": 36, "monto": 195.20, "descripcion": "Recarga celular", "cuenta": "Cash", "categoria": "Utilities", "comentario": "Saldo", "fecha": "2025-08-03"},
    {"id": 37, "monto": 140.00, "descripcion": "Ropa nueva", "cuenta": "Savings", "categoria": "Clothing", "comentario": "Verano", "fecha": "2025-08-04"},
    {"id": 38, "monto": 67.90, "descripcion": "Cine familia", "cuenta": "Cash", "categoria": "Entertainment", "comentario": "Película animada", "fecha": "2025-08-05"},
    {"id": 39, "monto": 299.00, "descripcion": "Supermercado", "cuenta": "Checking", "categoria": "Groceries", "comentario": "Quincena", "fecha": "2025-08-06"},
    {"id": 40, "monto": 200.00, "descripcion": "Parqueo", "cuenta": "Savings", "categoria": "Miscellaneous", "comentario": "Oficina", "fecha": "2025-08-07"},
    {"id": 41, "monto": 83.00, "descripcion": "Transporte", "cuenta": "Cash", "categoria": "Transportation", "comentario": "Bus mensual", "fecha": "2025-08-08"},
    {"id": 42, "monto": 400.00, "descripcion": "Médico niños", "cuenta": "Checking", "categoria": "Medical & Healthcare", "comentario": "Pediatra", "fecha": "2025-08-09"},
    {"id": 43, "monto": 119.00, "descripcion": "Veterinario perro", "cuenta": "Cash", "categoria": "Pets", "comentario": "Consulta", "fecha": "2025-08-10"},
    {"id": 44, "monto": 205.00, "descripcion": "Comida", "cuenta": "Savings", "categoria": "Groceries", "comentario": "Semanal", "fecha": "2025-08-11"},
    {"id": 45, "monto": 105.50, "descripcion": "Restaurante chino", "cuenta": "Cash", "categoria": "Restaurants", "comentario": "Cena familia", "fecha": "2025-08-12"},
    {"id": 46, "monto": 99.00, "descripcion": "Taxi", "cuenta": "Checking", "categoria": "Transportation", "comentario": "Trabajo", "fecha": "2025-08-13"},
    {"id": 47, "monto": 150.99, "descripcion": "Pago seguro", "cuenta": "Savings", "categoria": "Insurance", "comentario": "Salud", "fecha": "2025-08-14"},
    {"id": 48, "monto": 289.50, "descripcion": "Pago escuela", "cuenta": "Cash", "categoria": "Education", "comentario": "Inscripción", "fecha": "2025-08-15"},
    {"id": 49, "monto": 320.00, "descripcion": "Compra ropa", "cuenta": "Checking", "categoria": "Clothing", "comentario": "Temporada", "fecha": "2025-08-16"},
    {"id": 50, "monto": 222.00, "descripcion": "Veterinario", "cuenta": "Savings", "categoria": "Pets", "comentario": "Chequeo", "fecha": "2025-08-17"},
]