movimientos = [
    {"id": 51, "monto": 12000.00, "descripcion": "Pago freelance julio", "cuenta": "Savings", "categoria": "Freelance", "comentario": "Proyecto web", "fecha": "2024-07-01", "tipo": "Income"},
    {"id": 52, "monto": 1500.00, "descripcion": "Propina restaurante", "cuenta": "Cash", "categoria": "Tips", "comentario": "Cliente generoso", "fecha": "2024-07-02", "tipo": "Income"},
    {"id": 53, "monto": 5000.00, "descripcion": "Alquiler julio", "cuenta": "Checking", "categoria": "Rental Income", "comentario": "Renta apartamento", "fecha": "2024-07-03", "tipo": "Income"},
    {"id": 54, "monto": 2500.00, "descripcion": "Bonificación", "cuenta": "Savings", "categoria": "Bonus", "comentario": "Cumplimiento de metas", "fecha": "2024-07-04", "tipo": "Income"},
    {"id": 55, "monto": 2000.00, "descripcion": "Salario julio", "cuenta": "Checking", "categoria": "Salary", "comentario": "Pago mensual", "fecha": "2024-07-05", "tipo": "Income"},
    {"id": 56, "monto": 300.00, "descripcion": "Retorno inversión", "cuenta": "Savings", "categoria": "Investment", "comentario": "Fondo mutuo", "fecha": "2024-07-06", "tipo": "Income"},
    {"id": 57, "monto": 100.00, "descripcion": "Subsidio estatal", "cuenta": "Checking", "categoria": "Government Benefits", "comentario": "Apoyo familiar", "fecha": "2024-07-07", "tipo": "Income"},
    {"id": 58, "monto": 600.00, "descripcion": "Diseño freelance", "cuenta": "Cash", "categoria": "Freelance", "comentario": "Logo e identidad", "fecha": "2024-07-08", "tipo": "Income"},
    {"id": 59, "monto": 275.00, "descripcion": "Bonificación trimestral", "cuenta": "Savings", "categoria": "Bonus", "comentario": "Productividad", "fecha": "2024-07-09", "tipo": "Income"},
    {"id": 60, "monto": 90.00, "descripcion": "Propina evento", "cuenta": "Cash", "categoria": "Tips", "comentario": "Servicio bar", "fecha": "2024-07-10", "tipo": "Income"},
    {"id": 61, "monto": 1700.00, "descripcion": "Salario agosto", "cuenta": "Checking", "categoria": "Salary", "comentario": "Pago mensual", "fecha": "2024-08-01", "tipo": "Income"},
    {"id": 62, "monto": 325.00, "descripcion": "Dividendos", "cuenta": "Savings", "categoria": "Investment", "comentario": "Acciones", "fecha": "2024-08-02", "tipo": "Income"},
    {"id": 63, "monto": 85.00, "descripcion": "Propina tour", "cuenta": "Cash", "categoria": "Tips", "comentario": "Guía turístico", "fecha": "2024-08-03", "tipo": "Income"},
    {"id": 64, "monto": 520.00, "descripcion": "Alquiler agosto", "cuenta": "Checking", "categoria": "Rental Income", "comentario": "Apartamento zona 14", "fecha": "2024-08-04", "tipo": "Income"},
    {"id": 65, "monto": 180.00, "descripcion": "Ayuda gobierno", "cuenta": "Savings", "categoria": "Government Benefits", "comentario": "Programa social", "fecha": "2024-08-05", "tipo": "Income"},
    {"id": 66, "monto": 140.00, "descripcion": "Consultoría", "cuenta": "Cash", "categoria": "Freelance", "comentario": "Diagnóstico técnico", "fecha": "2024-08-06", "tipo": "Income"},
    {"id": 67, "monto": 110.00, "descripcion": "Apoyo familiar", "cuenta": "Checking", "categoria": "Other", "comentario": "Abuelo", "fecha": "2024-08-07", "tipo": "Income"},
    {"id": 68, "monto": 220.00, "descripcion": "Bonificación puntualidad", "cuenta": "Savings", "categoria": "Bonus", "comentario": "Empresa", "fecha": "2024-08-08", "tipo": "Income"},
    {"id": 69, "monto": 800.00, "descripcion": "Pago parcial contrato", "cuenta": "Checking", "categoria": "Freelance", "comentario": "Desarrollo web", "fecha": "2024-08-09", "tipo": "Income"},
    {"id": 70, "monto": 60.00, "descripcion": "Propina reunión", "cuenta": "Cash", "categoria": "Tips", "comentario": "Evento empresarial", "fecha": "2024-08-10", "tipo": "Income"},
    {"id": 71, "monto": 290.00, "descripcion": "Renta cuarto", "cuenta": "Checking", "categoria": "Rental Income", "comentario": "Mensualidad", "fecha": "2024-08-11", "tipo": "Income"},
    {"id": 72, "monto": 195.00, "descripcion": "Beneficio social", "cuenta": "Savings", "categoria": "Government Benefits", "comentario": "Programa hogar", "fecha": "2024-08-12", "tipo": "Income"},
    {"id": 73, "monto": 135.00, "descripcion": "Pago asesoría", "cuenta": "Cash", "categoria": "Freelance", "comentario": "Negocio local", "fecha": "2024-08-13", "tipo": "Income"},
    {"id": 74, "monto": 105.00, "descripcion": "Apoyo mamá", "cuenta": "Savings", "categoria": "Other", "comentario": "Transferencia", "fecha": "2024-08-14", "tipo": "Income"},
    {"id": 75, "monto": 2150.00, "descripcion": "Salario septiembre", "cuenta": "Checking", "categoria": "Salary", "comentario": "Pago mensual", "fecha": "2024-09-01", "tipo": "Income"}
]